version: 2.1

parameters:
  run_release_build:
    type: boolean
    default: false

executors:
  default:
    working_directory: /tmp/test_circleci
    docker:
      - image: circleci/android:api-28

jobs:
  assemble_staging_debug:
    - executor:
        name: default
    - steps:
        - run:
            name: Build debug APK
            command: ./gradlew :app:assembleDebug

workflows:
  version: 2
  debug:
    jobs:
      - assemble_staging_debug

