version: 2.1

parameters:
  run_release_build:
    type: boolean
    default: false

executors:
  default:
    working_directory: /tmp/workspace
    docker:
      - image: circleci/android:api-28

jobs:
  assemble_debug:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Build debug APK
          command: ./gradlew assembleDebug

workflows:
  version: 2
  hoge:
    jobs:
      - assemble_debug